### ISSUE TITLE
`list_intrin.txt` does not list all the intrinsics used by HPCombi

### ISSUE THREAD

**Issue by james-d-mitchell** [hivert/HPCombi#19]
... and it seems to include some intrinsics that aren't used in `include/*`. Namely:

* `_mm_popcnt_u64` found in `include/*.hpp` but not in `list_intrin.txt`!
* `_mm_cmpeq_epi8` declared in `list_intrin.txt` but not used in `include/*.hpp`!
* `_mm_cmplt_epi8` declared in `list_intrin.txt` but not used in `include/*.hpp`!
* `_mm_max_epi8` declared in `list_intrin.txt` but not used in `include/*.hpp`!

**Comment by hivert** [comment]
Fixed in V0.0.8
